
version: 0.0
os: linux
files:
  - source: /app.py
    destination: /home/ubuntu/restaurantrater/
  - source: /templates
    destination: /home/ubuntu/restaurantrater/templates
hook:
 AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
 